# test pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Hello_Test1
  steps:
  - bash: echo "Hello first time from 'Hello Test1' job"!
    displayName: 'Hello x 1'
  - bash: echo "Hello 2nd time from 'Hello Test1' job!"
    displayName: 'Hello x 2'
- job: Hello_Test2
  steps:
  - bash: echo "Hello first time from 'Hello Test2' job"!
    displayName: 'Hello x 1'
  - bash: echo "Hello 2nd time from 'Hello Test2' job!"
    displayName: 'Hello x 2'
- job: Finish_Success
  dependsOn:
    - Hello_Test1
    - Hello_Test2
  condition: succeeded()
  steps:
  - bash: |
      echo "Finishing pipeline with success!"
      echo "Have a nice day!"
    displayName: 'Finish pipeline run'
- job: Finish_Failed
  dependsOn:
    - Hello_Test1
    - Hello_Test2
  condition: failed()
  steps:
  - bash: |
      echo "Finishing pipeline with failures!"
      echo "Have a bad day!"
    displayName: 'Finish pipeline run'
